<?php

namespace MoncaretWS\ContentWidgetsBundle\Repository;
use MoncaretWS\ContentWidgetsBundle\Entity\Container\ContainerVersion;
use MoncaretWS\ContentWidgetsBundle\Entity\Container\MasterContainer;

/**
 * ContainerVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContainerVersionRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * @param MasterContainer $container
     *
     * @return null|object|ContainerVersion
     */
    public function getLatestContainerVersion(MasterContainer $container) {
        return $this->findOneBy(['container' => $container->getId()], ['versionIndex' => 'DESC']);
    }

    /**
     * @param MasterContainer $container
     *
     * @return null|object|ContainerVersion
     */
    public function getPublishedContainerVersion(MasterContainer $container) {
        return $this->findOneBy(['container' => $container->getId(), 'isPublishedVersion' => true], ['versionIndex' => 'DESC']);
    }

    /**
     * @param MasterContainer $container
     * @param int $version
     *
     * @return null|object|ContainerVersion
     */
    public function getContainerVersion(MasterContainer $container, $version) {
        return $this->findOneBy(['container' => $container->getId(), 'versionIndex' => $version]);
    }

    /**
     * @param MasterContainer $container
     *
     * @return array|ContainerVersion[]
     */
    public function getContainerVersions(MasterContainer $container) {
        return $this->findBy(['container' => $container->getId()], ['versionIndex' => 'DESC']);
    }
}
