<?php

namespace MoncaretWS\ContentWidgetsBundle\Repository;

/**
 * WidgetContainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetContainerRepository extends \Doctrine\ORM\EntityRepository {

    public function findOneByName($name) {
        return $this->findOneBy(['name'=> $name]);
    }

}
