services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    widget_container_factory:
        class: MoncareyWS\ContentWidgetsBundle\Factory\WidgetContainerFactory
        arguments:
            $doctrine: '@doctrine'

    widget_factory:
        class: MoncareyWS\ContentWidgetsBundle\Factory\WidgetFactory
        arguments:
            $doctrine: '@doctrine'
            $manager: '@widget_manager'
            $containerFactory: '@widget_container_factory'
            $formFactory: '@form.factory'
            $router: '@router'

    widget_container_manager:
        class: MoncareyWS\ContentWidgetsBundle\Manager\WidgetContainerManager
        arguments:
            $registry: '@doctrine'
            $containerFactory: '@widget_container_factory'

    widget_manager:
        class: MoncareyWS\ContentWidgetsBundle\Manager\WidgetManager
        arguments:
            $registry: '@doctrine'

    widget_renderer:
        class: MoncareyWS\ContentWidgetsBundle\Twig\Helper\WidgetRenderer
        arguments:
            $widgetManager: '@widget_manager'
            $containerManager: '@widget_container_manager'

    twig.filter.widget_extention:
        class: MoncareyWS\ContentWidgetsBundle\Twig\Extension\WidgetExtension
        arguments:
            $widgetRenderer: '@widget_renderer'
        tags:
            - { name: twig.extension }

    widget_doctrine_event_listnener:
        class: MoncareyWS\ContentWidgetsBundle\EventListener\DoctrineEventSubscriber
        tags:
            - { name: doctrine.event_subscriber , connection: default }

    html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments:
            $purifier: '@exercise_html_purifier.default'

    trumbowyg_editor:
        class: MoncareyWS\ContentWidgetsBundle\Form\Type\TrumbowygEditorType
        arguments:
            $htmlPurifier: '@html_purifier'
        tags:
            - {name: form.type, alias: trumbowyg_editor}
